### ISSUE TITLE
Would it be possible to build this as a library?

### ISSUE THREAD

**Issue by frink** [biokoda/actordb_driver#1]
I'm thinking about the possibility of embedding this in a C application rather than erlang. I like what you've done with sqlite on lmdb. Makes sense. But would like to embed this for my own uses.

Any hope? Or am I dreaming too many dreams?

**Comment by SergejJurecko** [comment]
Are you thinking having multiple sqlite databases in lmdb or just have an
sqlite backed by lmdb?

**Comment by SergejJurecko** [comment]
Yes it is completely possible. c_src/tool.c file uses sqlite/lmdb code without any erlang parts. It does not execute any sql statements, but there is no reason why it could not. Look at the Makefile to see how it is compiled.
