### ISSUE TITLE
sqlite3_prepare_v2 fails

### ISSUE THREAD

**Issue by buybackoff** [biokoda/actordb_driver#3]
Original issue:

When used as a drop-in replacement of original Sqlite, the write performance drops by 10x times in [this test](https://github.com/Spreads/Spreads/blob/master/tests/Spreads.Extensions.Tests/Storage/StorageTests.cs#L36). However, I have to comment out these line: `connection.ExecuteNonQuery("PRAGMA journal_mode = WAL;");` because it causes segfault. Is WAL mode set by default in actordb_driver, or I need to turn it on in a special way?

Update:

In the source, you use sqlite_exec whenever you set PRAGMA... When I call "PRAGMA journal_mode = WAL;" via .NETs client it calls `sqlite3_prepare_v2` and segfault happens there.

**Comment by SergejJurecko** [comment]
I guess the actordb code is not commited? The code must be open very similar to how noerl.c uses it. I can't really say anything without seeing how it's integrated

**Comment by buybackoff** [comment]
I just build the driver with:

```
    TOOLCMD = gcc -pthread -static -static-libgcc -shared -Wl,-soname -Wl,--dll  c_src/tool.c c_src/mdb.c c_src/midl.c c_src/lz4.c  -D_TESTAPP_=1 -DMDB_MAXKEYSIZE=0 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_DEFAULT_WAL_AUTOCHECKPOINT=0 -lpthread  -o sqlite3.dll

```

with those lines commented out:

```
//#define SQLITE_API static
//#define SQLITE_EXTERN static
```

and replace the original sqlite3.dll.

I was able to call `sqlite3_exec` with PRAGMA, then I call `sqlite3_exec` with `CREATE TABLE...` [statement](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Extensions/Storage/SeriesStorage.cs#L74) and am getting segfault there...

**Comment by SergejJurecko** [comment]
You're building tool.c not noerl.c
You can't run it that way. You must run it like noerl.c runs it (look at main in noerl.c). You must do lmdb initialization and understand whats going on. It's not that easy...

**Comment by buybackoff** [comment]
Looks like noerl.c is not synced with other parts as of now. In some places it accesses non-existing members, e.g. usageCount. `Wal.mtx` is defined only when TEST_APP is not defined, but then it is accesses without `#ifndef` check. What is the latest version when `noerl.c` should work?

**Comment by buybackoff** [comment]
@SergejJurecko BTW, what write performance gain you see compared to the original sqlite3, if any? Is it the same order as [here](https://github.com/LMDB/sqlightning) or better?

**Comment by SergejJurecko** [comment]
noerl.c has been fixed. We didn't test performance gain. It would probably not be as fast as sqlightning because it interfaces to sqlite differently. We must store data in such a way that we can run raft replication and multiple sqlite databases on it. We did not test speed difference because it does not mean anything to us...

**Comment by buybackoff** [comment]
Thanks! I was able to run noerl. It would be nice to put all init logic into a rewritten sqlite3_initialize, so that drop-in replacement could easily work some day.
